version: '3.8'
services:
  db:
    container_name: mysql01
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpw
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
      TZ: 'Asia/Tokyo'
    image: mysql:8.0
    ports:
      - "3306:3306"
    # restart: always
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./log:/var/log/mysql
